services:
    # First we define some basic services to make these utilities available in
    # the entire application
    slugger:
        class: AppBundle\Utils\Slugger

    markdown:
        class: AppBundle\Utils\Markdown

    # These are the Twig extensions that create new filters and functions for
    # using them in the templates
    app.twig.app_extension:
        public:    false
        class:     AppBundle\Twig\AppExtension
        arguments: ['@markdown', '%app_locales%']
        tags:
            - { name: twig.extension }

    app.twig.intl_extension:
        public: false
        class:  Twig_Extensions_Extension_Intl
        tags:
            - { name: twig.extension }

    app.redirect_to_preferred_locale_listener:
        class: AppBundle\EventListener\RedirectToPreferredLocaleListener
        arguments: ['@router', '%app_locales%', '%locale%']
        tags:
            - { name: kernel.event_listener, event: kernel.request, method: onKernelRequest }

    app.guard_authenticator:
        class: AppBundle\Security\GuardAuthenticator
        arguments: ['@doctrine.orm.entity_manager', '@security.encoder_factory', '@router']

#    app.timesheet_manager:
#        class: AppBundle\Services\TimesheetManager
#
#    app.timesheet_type:
#        class: AppBundle\Form\TimesheetType
#        arguments: ['@app.timesheet_manager']
#        tags:
#            - { name: form.type }